### ISSUE TITLE
希望能测试一下fallbacks使用tcp端口，domainsocket性能的差异

### ISSUE THREAD

**Issue by ghost** [badO1a5A90/v2ray-doc#1]
希望能测试一下fallbacks使用tcp端口、domainsocket、abstract domainsocket和padding abstract domainsocket性能的差异。
同时希望能够测试一下domainsocket、abstract domainsocket和padding abstract domainsocket文件位置在磁盘和内存中(比如/dev/shm)性能的差异。
谢谢

**Comment by badO1a5A90** [comment]
https://github.com/badO1a5A90/v2ray-doc/blob/master/performance_test/DS/20201030.md

**Comment by ghost** [comment]
> https://github.com/badO1a5A90/v2ray-doc/blob/master/performance_test/DS/20201030.md

谢谢

请问测试中doamin socket的路径是在内存中还是硬盘中？

**Comment by badO1a5A90** [comment]
是tmpfs
走磁盘应该就受限于磁盘IO了。

**Comment by ghost** [comment]
> 是tmpfs
> 走磁盘应该就受限于磁盘IO了。

谢谢
